# Generated by Django 2.2.4 on 2019-08-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('MobileNo', models.IntegerField()),
                ('EmailId', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
                ('TotalAmount', models.FloatField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=30)),
                ('Description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelNo', models.CharField(max_length=30)),
                ('Price', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('Status', models.CharField(choices=[('Available', 'Ready to sale'), ('Sold', 'Not available'), ('Restock', 'coming in stock')], default='Available', max_length=40)),
                ('Description', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentType', models.CharField(choices=[('ByCash', 'Pay through cash'), ('ByCard', 'Pay through card'), ('Online mode', 'Pay Online')], default='ByCash', max_length=70)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Sales')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='proddetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductDetails'),
        ),
    ]
